URL_CAT_BUTTON = "https://testpages.eviltester.com/styled/index.html"

LOCATOR_BASIC = "#basicpagetest"
LOCATOR_TABLE1 = "body > div.page-body > div.explanation > p"
LOCATOR_ELEMENT = "#elementattributestest"
LOCATOR_BUTTON = "W"
LOCATOR_BUTTON_TABLE = "body > div.page-body > div:nth-child(13) > button"
LOCATOR_FIND = "#findbytest"
LOCATOR_TABLE2 = "body > div:nth-child(3) > div > a:nth-child(1)"
LOCATOR_BUTTON_JUMP1 = "#a27"
LOCATOR_TABLE3 = "body > div:nth-child(3) > div > a:nth-child(2)"
LOCATOR_WEBDRIVER = "#webdriverexamplepage"
LOCATOR_NUM = "#numentry"
LOCATOR_PROCESS = "#submit-to-server"